
import React from 'react';

export const PodcastDemo: React.FC = () => {
  return (
    <section className="py-24 border-v">
      <div className="mb-12">
        <span className="font-mono text-[10px] text-[var(--trust-blue)] tracking-[0.4em] uppercase font-bold">Multimodal Proof</span>
        <h2 className="text-4xl font-bold italic text-[var(--text-header)] mt-4">Recursive Demonstration.</h2>
        <p className="text-lg leading-relaxed text-[var(--text-body)] opacity-80 mt-6 max-w-2xl">
          These podcasts were generated by <strong>NotebookLM</strong> analyzing the Signet Protocol v0.3.2 Specification. They serve as recursive evidence: the protocol documenting itself through AI agents.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="space-y-4">
           <div className="aspect-video bg-black rounded-xl overflow-hidden border border-[var(--border-light)] shadow-2xl relative group">
              <iframe 
                width="100%" 
                height="100%" 
                src="https://www.youtube.com/embed/UatpGRr-wA0" 
                title="Signet Protocol - English Deep Dive" 
                frameBorder="0" 
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                allowFullScreen
                className="opacity-90 group-hover:opacity-100 transition-opacity"
              ></iframe>
           </div>
           <div className="flex justify-between items-center px-2">
              <span className="font-mono text-[10px] uppercase font-bold text-[var(--text-header)]">English Edition</span>
              <span className="font-mono text-[9px] opacity-40 uppercase">Source: NotebookLM</span>
           </div>
        </div>

        <div className="space-y-4">
           <div className="aspect-video bg-black rounded-xl overflow-hidden border border-[var(--border-light)] shadow-2xl relative group">
              <iframe 
                width="100%" 
                height="100%" 
                src="https://www.youtube.com/embed/5F_6YDhA2A0" 
                title="Signet Protocol - Chinese Deep Dive" 
                frameBorder="0" 
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                allowFullScreen
                className="opacity-90 group-hover:opacity-100 transition-opacity"
              ></iframe>
           </div>
           <div className="flex justify-between items-center px-2">
              <span className="font-mono text-[10px] uppercase font-bold text-[var(--text-header)]">Chinese Edition (中文)</span>
              <span className="font-mono text-[9px] opacity-40 uppercase">Source: NotebookLM</span>
           </div>
        </div>
      </div>
      
      <div className="mt-8 text-center">
         <p className="font-mono text-[9px] opacity-30 uppercase tracking-widest">
            Video Assets Signed by Master Signatory: signetai.io:ssl
         </p>
      </div>
    </section>
  );
};
